In [58]:
import pandas as pd
import numpy as np

In [59]:
data = {
    "Employee_ID": [
        101, 102, 103, 104, 105, 106,
        107, 108, 109, 110, 111, 112
    ],
    "Name": [
        "Alex", "Sarah", "Youssef", "Emma",
        "Daniel", "Lina", "Adam", "Sofia",
        "James", "Maya", "Omar", "Leo"
    ],
    "Company": [
        "Jane Street", "Jane Street", "HRT", "HRT",
        "Citadel", "Citadel", "Jane Street", "HRT",
        "Citadel", "Jane Street", "HRT", "Citadel"
    ],
    "Department": [
        "Trading", "Research", "Trading", "Engineering",
        "Research", "Trading", "Engineering", "Research",
        "Engineering", "Trading", "Research", "Trading"
    ],
    "Salary_USD": [
        150000, 125000, 180000, 110000,
        140000, 160000, 115000, 135000,
        120000, 145000, 130000, 155000
    ],
    "Age": [
        26, 24, 29, 27, 31, 28,
        25, 30, 26, 29, 27, 32
    ],
    "Years_Experience": [
        3, 2, 5, 4, 6, 4,
        2, 5, 3, 4, 3, 7
    ],
    "Remote": [
        True, True, False, True,
        False, True, True, False,
        False, True, False, True
    ]
}

In [60]:
df = pd.DataFrame(data)
df

,Employee_ID,Name,Company,Department,Salary_USD,Age,Years_Experience,Remote
0,101,Alex,Jane Street,Trading,150000,26,3,True
1,102,Sarah,Jane Street,Research,125000,24,2,True
2,103,Youssef,HRT,Trading,180000,29,5,False
3,104,Emma,HRT,Engineering,110000,27,4,True
4,105,Daniel,Citadel,Research,140000,31,6,False
5,106,Lina,Citadel,Trading,160000,28,4,True
6,107,Adam,Jane Street,Engineering,115000,25,2,True
7,108,Sofia,HRT,Research,135000,30,5,False
8,109,James,Citadel,Engineering,120000,26,3,False
9,110,Maya,Jane Street,Trading,145000,29,4,True
10,111,Omar,HRT,Research,130000,27,3,False
11,112,Leo,Citadel,Trading,155000,32,7,True

In [61]:
#level 1

#first five rows of the dataset
print(df.head(5))
#last three rows of the dataset
print(df.tail(3))
#number of rows and columns
print(df.shape)
#every column type
print(df.dtypes)
#descriptif statistics for salary_usd
print(df['Salary_USD'].describe())

   Employee_ID     Name      Company   Department  Salary_USD  Age  \
0          101     Alex  Jane Street      Trading      150000   26
1          102    Sarah  Jane Street     Research      125000   24
2          103  Youssef          HRT      Trading      180000   29
3          104     Emma          HRT  Engineering      110000   27
4          105   Daniel      Citadel     Research      140000   31

   Years_Experience  Remote
0                 3    True
1                 2    True
2                 5   False
3                 4    True
4                 6   False
    Employee_ID  Name      Company Department  Salary_USD  Age  \
9           110  Maya  Jane Street    Trading      145000   29
10          111  Omar          HRT   Research      130000   27
11          112   Leo      Citadel    Trading      155000   32

    Years_Experience  Remote
9                  4    True
10                 3   False
11                 7    True
(12, 8)
Employee_ID         int64
Name                  str
Company               str
Department            str
Salary_USD          int64
Age                 int64
Years_Experience    int64
Remote               bool
dtype: object
count        12.00000
mean     138750.00000
std       20463.38193
min      110000.00000
25%      123750.00000
50%      137500.00000
75%      151250.00000
max      180000.00000
Name: Salary_USD, dtype: float64

In [62]:
#level 2

#employee of index 4
print(df.iloc[4])
#salary of the employee at index 4
print(df['Salary_USD'].loc[2])
#employees earning more than $140000
print(df[df['Salary_USD'] > 140000])
#employees earn more than $130000 and age under 30
print(df[(df['Salary_USD'] > 130000) & (df['Age'] < 30)])
#employees working in research or engineering
print(df[(df['Department'] == 'Research') | (df['Department'] == 'Engineering')])
#name and salaries of employeeswho works remotly and have atleast three years of experience
print(df[(df['Remote'] == True) & (df['Years_Experience'] >= 3)][['Name', 'Salary_USD']])

Employee_ID              105
Name                  Daniel
Company              Citadel
Department          Research
Salary_USD            140000
Age                       31
Years_Experience           6
Remote                 False
Name: 4, dtype: object
180000
    Employee_ID     Name      Company Department  Salary_USD  Age  \
0           101     Alex  Jane Street    Trading      150000   26
2           103  Youssef          HRT    Trading      180000   29
5           106     Lina      Citadel    Trading      160000   28
9           110     Maya  Jane Street    Trading      145000   29
11          112      Leo      Citadel    Trading      155000   32

    Years_Experience  Remote
0                  3    True
2                  5   False
5                  4    True
9                  4    True
11                 7    True
   Employee_ID     Name      Company Department  Salary_USD  Age  \
0          101     Alex  Jane Street    Trading      150000   26
2          103  Youssef          HRT    Trading      180000   29
5          106     Lina      Citadel    Trading      160000   28
9          110     Maya  Jane Street    Trading      145000   29

   Years_Experience  Remote
0                 3    True
2                 5   False
5                 4    True
9                 4    True
    Employee_ID    Name      Company   Department  Salary_USD  Age  \
1           102   Sarah  Jane Street     Research      125000   24
3           104    Emma          HRT  Engineering      110000   27
4           105  Daniel      Citadel     Research      140000   31
6           107    Adam  Jane Street  Engineering      115000   25
7           108   Sofia          HRT     Research      135000   30
8           109   James      Citadel  Engineering      120000   26
10          111    Omar          HRT     Research      130000   27

    Years_Experience  Remote
1                  2    True
3                  4    True
4                  6   False
6                  2    True
7                  5   False
8                  3   False
10                 3   False
    Name  Salary_USD
0   Alex      150000
3   Emma      110000
5   Lina      160000
9   Maya      145000
11   Leo      155000

In [63]:
#level 3

#Add Annual_Bonus column
df['Annual_Bonus'] = df['Salary_USD'] * 0.1
#add total_Compensation column
df['Total_Compensation'] = df['Salary_USD'] + df['Annual_Bonus']
#insert the seniority column
seniority_list= []
for i in df['Years_Experience']:
    if i >= 5:
        seniority_list.append('Senior')
    else:
        seniority_list.append('Junior')
df.insert(2, 'Seniority', seniority_list)
#add monthly salary using assign
new_df = df.assign(monthly_salary = df['Salary_USD']/12)
#copy of df without remote column
copy_df = df.drop('Remote', axis=1)
#remove employee with the index 5
copy_df.drop(5, inplace=True)

In [64]:
#level 4

#number of employees in each company
count = df.groupby('Company')['Employee_ID'].count()
print(count)
#avg salary of each company
avg_salary = df.groupby('Company')['Salary_USD'].mean()
print(avg_salary)
#max salary of each departement
max_salary = df.groupby('Department')['Salary_USD'].max()
print(max_salary)
#how many employees in each depatment
employee_count = df.groupby('Department')['Employee_ID'].count()
print(employee_count)
#groupby company and department
employee_count = df.groupby(['Company', 'Department'])['Salary_USD'].mean()
print(employee_count)

Company
Citadel        4
HRT            4
Jane Street    4
Name: Employee_ID, dtype: int64
Company
Citadel        143750.0
HRT            138750.0
Jane Street    133750.0
Name: Salary_USD, dtype: float64
<pandas.api.typing.SeriesGroupBy object at 0x000002904806DF40>
Department
Engineering    3
Research       4
Trading        5
Name: Employee_ID, dtype: int64
Company      Department
Citadel      Engineering    1
             Research       1
             Trading        2
HRT          Engineering    1
             Research       2
             Trading        1
Jane Street  Engineering    1
             Research       1
             Trading        2
Name: Salary_USD, dtype: int64

In [65]:
#level 5

#all unique company names
print(df['Company'].unique())
#compnies employees number using value_count()
print(df['Company'].value_counts())
#sort employes by salary from the highest to the lowest
df['Salary_USD'].sort_values(ascending=False)
#sort employes by there alphabeticly by name
df['Name'].sort_values()
#series containing only unique salaries
series_list = df['Salary_USD'].unique()
series = pd.Series(series_list)
print(series)
#last question of level 5
idk = pd.DataFrame({"1": 1, "2": np.nan, "3": 3}, index=[1])
idk.fillna(value=2, inplace=True)

<StringArray>
['Jane Street', 'HRT', 'Citadel']
Length: 3, dtype: str
0     150000
1     125000
2     180000
3     110000
4     140000
5     160000
6     115000
7     135000
8     120000
9     145000
10    130000
11    155000
dtype: int64

   1    2  3
1  1  2.0  3

In [112]:
#level 6
#company with the most employees
idk = df.groupby('Company')['Employee_ID'].count()
print(idk[idk == idk.max()])
#department with the highest average salary
idk = df.groupby('Department')['Salary_USD'].mean()
print(idk[idk == idk.max()])
#three highest paid employees
print(df[['Name', 'Company', 'Salary_USD']].sort_values(by='Salary_USD', ascending=False).head(3))
#avg salary of remote workers + comparison
remote_avg = df.groupby('Remote')['Salary_USD'].mean()
print(f"the avg salary of remote workers is : {remote_avg[True]}")
if remote_avg[True] > remote_avg[False]:
    print("remote workers get paid more than non remote worker")
else:
    print("non remote workers get paid more than remote worker")
#new data frame + percentage salary column
ndf = df[df['Salary_USD'] >= 130000].copy()
avg = df['Salary_USD'].mean()
ndf['percentage'] = (ndf['Salary_USD'] * 100)/avg
#Sumary
print("""
Jane Street, HRT, and Citadel each employ four people.
Trading has the highest average salary at $158,000.
The highest-paid employee is Youssef, earning $180,000.
Remote employees average approximately $137,143, compared with $141,000 for non-remote""")

Company
Citadel        4
HRT            4
Jane Street    4
Name: Employee_ID, dtype: int64
Department
Trading    158000.0
Name: Salary_USD, dtype: float64
       Name  Company  Salary_USD
2   Youssef      HRT      180000
5      Lina  Citadel      160000
11      Leo  Citadel      155000
the avg salary of remote workers is : 137142.85714285713
non remote workers get paid more than remote worker

Jane Street, HRT, and Citadel each employ four people.
Trading has the highest average salary at $158,000.
The highest-paid employee is Youssef, earning $180,000.
Remote employees average approximately $137,143, compared with $141,000 for non-remote

In [111]:
ndf = df[df['Salary_USD'] >= 130000]
avg = df['Salary_USD'].mean()
ndf['percentage'] = (ndf['Salary_USD'] * 100)/avg
ndf

,Employee_ID,Name,Seniority,Company,Department,Salary_USD,Age,Years_Experience,Remote,Annual_Bonus,Total_Compensation,percentage
0,101,Alex,Junior,Jane Street,Trading,150000,26,3,True,15000.0,165000.0,108.108108
2,103,Youssef,Senior,HRT,Trading,180000,29,5,False,18000.0,198000.0,129.729730
4,105,Daniel,Senior,Citadel,Research,140000,31,6,False,14000.0,154000.0,100.900901
5,106,Lina,Junior,Citadel,Trading,160000,28,4,True,16000.0,176000.0,115.315315
7,108,Sofia,Senior,HRT,Research,135000,30,5,False,13500.0,148500.0,97.297297
9,110,Maya,Junior,Jane Street,Trading,145000,29,4,True,14500.0,159500.0,104.504505
10,111,Omar,Junior,HRT,Research,130000,27,3,False,13000.0,143000.0,93.693694
11,112,Leo,Senior,Citadel,Trading,155000,32,7,True,15500.0,170500.0,111.711712